#!/bin/bash 
set -x 
yum -y install bind bind-utils 
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config

cp -f /vagrant/dhclient.conf_ns2 /etc/dhcp/dhclient.conf
cp -f /vagrant/named2.conf  /etc/named.conf
systemctl enable named
systemctl start named


systemctl start firewalld
firewall-cmd --permanent --add-port=53/tcp 
firewall-cmd --permanent --add-port=53/udp 
firewall-cmd --reload
#

chgrp named -R /var/named
chown -v root:named /etc/named.conf
restorecon -rv /var/named
restorecon /etc/named.conf

systemctl restart network

cp -f /vagrant/ddns-key.txt ~/
cp -f /vagrant/update_ns1.txt ~/

cd 

#nsupdate -k ddns-key.txt -v update_ns1.txt
